title: COMS30050 - Applied Data Science
markdown: kramdown
theme: jekyll-theme-dinky
author: Nirav Ajmeri

header_pages:
  - index.md
  - course-details.md
  - assessment-information.md
  - refresher.md

